# Generated by Django 3.1.4 on 2021-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=10, verbose_name='카테고리')),
                ('order_num', models.CharField(max_length=20, verbose_name='주문번호')),
                ('post_title', models.CharField(default='', max_length=20, verbose_name='제목')),
                ('post_content', models.TextField(default='', max_length=250, verbose_name='내용')),
                ('person_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('answer', models.CharField(default='', max_length=100, verbose_name='답변')),
            ],
            options={
                'db_table': 'CustomerService',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=10, verbose_name='분류')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('title', models.CharField(default='', max_length=20, verbose_name='제목')),
                ('content', models.TextField(default='', max_length=250, verbose_name='내용')),
                ('person_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'db_table': 'Notice',
            },
        ),
    ]
